export const tasksData = [
  {
    id: "t1",
    title: "Create project architecture",
    description: "Define project structure and state management strategy.",
    priority: "HIGH",
    status: "in-progress",
    projectId: "p1",
    assigneeId: "u3",
    createdAt: "2025-12-05T10:00:00.000Z",
  },
  {
    id: "t2",
    title: "Implement EntityAdapter",
    description: "Normalize Redux state using EntityAdapter.",
    priority: "HIGH",
    status: "done",
    projectId: "p1",
    assigneeId: "u1",
    createdAt: "2025-12-04T14:30:00.000Z",
  },
  {
    id: "t3",
    title: "Configure GitHub Actions",
    description: "Add CI pipeline for linting and build.",
    priority: "HIGH",
    status: "todo",
    projectId: "p2",
    assigneeId: "u6",
    createdAt: "2025-12-06T09:20:00.000Z",
  },
  {
    id: "t4",
    title: "Design dashboard layout",
    description: "Create dashboard UI wireframes.",
    priority: "MEDIUM",
    status: "in-progress",
    projectId: "p3",
    assigneeId: "u9",
    createdAt: "2025-12-03T11:15:00.000Z",
  },
  {
    id: "t5",
    title: "Implement login flow",
    description: "Add login form and authentication logic.",
    priority: "HIGH",
    status: "in-progress",
    projectId: "p4",
    assigneeId: "u1",
    createdAt: "2025-12-07T08:40:00.000Z",
  },
  {
    id: "t6",
    title: "Optimize bundle size",
    description: "Analyze bundle and remove unused dependencies.",
    priority: "MEDIUM",
    status: "todo",
    projectId: "p5",
    assigneeId: "u10",
    createdAt: "2025-12-06T16:10:00.000Z",
  },
  {
    id: "t7",
    title: "Add unit tests",
    description: "Write unit tests for reducers and selectors.",
    priority: "LOW",
    status: "todo",
    projectId: "p6",
    assigneeId: "u4",
    createdAt: "2025-12-02T13:00:00.000Z",
  },
  {
    id: "t8",
    title: "Create analytics charts",
    description: "Implement charts for project statistics.",
    priority: "LOW",
    status: "todo",
    projectId: "p7",
    assigneeId: "u12",
    createdAt: "2025-12-01T17:45:00.000Z",
  },
];
