export const tasksData = [
  {
    id: "t1",
    title: "Create project architecture",
    description: "Define project structure and state management strategy.",
    priority: "HIGH",
    status: "in-progress",
    projectId: "p1",
    creatorId: "u1",
    assigneeId: "u3",
    createdAt: "2025-12-05T10:00:00.000Z",
  },
  {
    id: "t2",
    title: "Implement EntityAdapter",
    description: "Normalize Redux state using EntityAdapter.",
    priority: "HIGH",
    status: "done",
    projectId: "p1",
    creatorId: "u1",
    assigneeId: "u1",
    createdAt: "2025-12-04T14:30:00.000Z",
  },
  {
    id: "t3",
    title: "Configure GitHub Actions",
    description: "Add CI pipeline for linting and build.",
    priority: "HIGH",
    status: "todo",
    projectId: "p2",
    creatorId: "u6",
    assigneeId: "u6",
    createdAt: "2025-12-06T09:20:00.000Z",
  },
  {
    id: "t4",
    title: "Design dashboard layout",
    description: "Create dashboard UI wireframes.",
    priority: "MEDIUM",
    status: "in-progress",
    projectId: "p3",
    creatorId: "u2",
    assigneeId: "u9",
    createdAt: "2025-12-03T11:15:00.000Z",
  },
  {
    id: "t5",
    title: "Implement login flow",
    description: "Add login form and authentication logic.",
    priority: "HIGH",
    status: "in-progress",
    projectId: "p4",
    creatorId: "u1",
    assigneeId: "u1",
    createdAt: "2025-12-07T08:40:00.000Z",
  },
  {
    id: "t6",
    title: "Optimize bundle size",
    description: "Analyze bundle and remove unused dependencies.",
    priority: "MEDIUM",
    status: "todo",
    projectId: "p5",
    creatorId: "u6",
    assigneeId: "u10",
    createdAt: "2025-12-06T16:10:00.000Z",
  },
  {
    id: "t7",
    title: "Add unit tests",
    description: "Write unit tests for reducers and selectors.",
    priority: "LOW",
    status: "todo",
    projectId: "p6",
    creatorId: "u11",
    assigneeId: "u4",
    createdAt: "2025-12-02T13:00:00.000Z",
  },
  {
    id: "t8",
    title: "Create analytics charts",
    description: "Implement charts for project statistics.",
    priority: "LOW",
    status: "todo",
    projectId: "p7",
    creatorId: "u6",
    assigneeId: "u12",
    createdAt: "2025-12-01T17:45:00.000Z",
  },

  // --- NEW TASKS ---

  {
    id: "t9",
    title: "Refactor project reducers",
    description: "Improve reducers readability and split logic into slices.",
    priority: "MEDIUM",
    status: "in-progress",
    projectId: "p1",
    creatorId: "u1",
    assigneeId: "u3",
    createdAt: "2025-12-07T12:00:00.000Z",
  },
  {
    id: "t10",
    title: "Add drag & drop for tasks",
    description: "Implement drag & drop task status changes.",
    priority: "HIGH",
    status: "todo",
    projectId: "p1",
    creatorId: "u6",
    assigneeId: "u6",
    createdAt: "2025-12-07T13:20:00.000Z",
  },
  {
    id: "t11",
    title: "Set up Cypress tests",
    description: "Configure end-to-end testing with Cypress.",
    priority: "MEDIUM",
    status: "todo",
    projectId: "p2",
    creatorId: "u6",
    assigneeId: "u5",
    createdAt: "2025-12-06T18:00:00.000Z",
  },
  {
    id: "t12",
    title: "Improve accessibility",
    description: "Fix WCAG issues and improve keyboard navigation.",
    priority: "MEDIUM",
    status: "in-progress",
    projectId: "p3",
    creatorId: "u2",
    assigneeId: "u7",
    createdAt: "2025-12-05T15:30:00.000Z",
  },
  {
    id: "t13",
    title: "Add role-based guards",
    description: "Restrict actions based on user roles.",
    priority: "HIGH",
    status: "todo",
    projectId: "p4",
    creatorId: "u1",
    assigneeId: "u11",
    createdAt: "2025-12-07T09:10:00.000Z",
  },
  {
    id: "t14",
    title: "Lazy load heavy components",
    description: "Apply React.lazy and Suspense to heavy pages.",
    priority: "LOW",
    status: "done",
    projectId: "p5",
    creatorId: "u6",
    assigneeId: "u10",
    createdAt: "2025-12-04T17:00:00.000Z",
  },
  {
    id: "t15",
    title: "Regression testing",
    description: "Run regression tests before release.",
    priority: "LOW",
    status: "blocked",
    projectId: "p6",
    creatorId: "u11",
    assigneeId: "u8",
    createdAt: "2025-12-03T10:45:00.000Z",
  },
  {
    id: "t16",
    title: "Prepare analytics report",
    description: "Generate analytics summary for stakeholders.",
    priority: "MEDIUM",
    status: "in-progress",
    projectId: "p7",
    creatorId: "u6",
    assigneeId: "u12",
    createdAt: "2025-12-07T14:00:00.000Z",
  },
];
