export const usersMock = [
  {
    id: "u1",
    name: "Олег Корж",
    username: "admin",
    password: "admin",
    role: "admin",
    projects: ["1", "2", "3"],
    avatarUrl: "https://i.pravatar.cc/150?img=1",
  },
  {
    id: "u2",
    name: "Лада Койчева",
    username: "admin1",
    password: "admin1",
    role: "admin",
    projects: ["1", "2"],
    avatarUrl: "https://i.pravatar.cc/150?img=2",
  },
  {
    id: "u3",
    name: "Alice Johnson",
    username: "alice",
    password: "1234",
    role: "developer",
    projects: ["1"],
    avatarUrl: "https://i.pravatar.cc/150?img=3",
  },
  {
    id: "u4",
    name: "Priya Singh",
    username: "priya",
    password: "1234",
    role: "qa",
    projects: ["1", "2"],
    avatarUrl: "https://i.pravatar.cc/150?img=4",
  },
  {
    id: "u5",
    name: "Tom R.",
    username: "tom",
    password: "1234",
    role: "developer",
    projects: ["3"],
    avatarUrl: "https://i.pravatar.cc/150?img=5",
  },
  {
    id: "u6",
    name: "John Cena",
    username: "john",
    password: "1234",
    role: "manager",
    projects: ["1", "2", "3"],
    avatarUrl: "https://i.pravatar.cc/150?img=6",
  },
  {
    id: "u7",
    name: "Emma Wilson",
    username: "emma",
    password: "1234",
    role: "developer",
    projects: ["2"],
    avatarUrl: "https://i.pravatar.cc/150?img=7",
  },
  {
    id: "u8",
    name: "Michael Brown",
    username: "michael",
    password: "1234",
    role: "qa",
    projects: ["3"],
    avatarUrl: "https://i.pravatar.cc/150?img=8",
  },
  {
    id: "u9",
    name: "Sophia Martinez",
    username: "sophia",
    password: "1234",
    role: "designer",
    projects: ["1"],
    avatarUrl: "https://i.pravatar.cc/150?img=9",
  },
  {
    id: "u10",
    name: "Daniel Lee",
    username: "daniel",
    password: "1234",
    role: "developer",
    projects: ["2", "3"],
    avatarUrl: "https://i.pravatar.cc/150?img=10",
  },
  {
    id: "u11",
    name: "Olivia Parker",
    username: "olivia",
    password: "1234",
    role: "manager",
    projects: ["2"],
    avatarUrl: "https://i.pravatar.cc/150?img=11",
  },
  {
    id: "u12",
    name: "Ethan Clark",
    username: "ethan",
    password: "1234",
    role: "developer",
    projects: [],
    avatarUrl: "https://i.pravatar.cc/150?img=12",
  },
];
